In [188]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [189]:
df_ag = pd.read_csv('../resultados/mesma populacao/mutacao simples/mesma_pop_ag.csv',index_col=0)
df_ag.style.format("{:.2f}")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [190]:
df_ag_min = df_ag.loc[df_ag['makespan'].isin(df_ag.groupby('instance')['makespan'].min().values)]

In [191]:
df_eda = pd.read_csv('../resultados/mesma populacao/mutacao simples/eda_mutacao_antes_geracao_mesma_pop.csv',index_col=0)
df_eda.style.format("{:.2f}")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [192]:
df_eda_min = df_eda.loc[df_eda['makespan'].isin(df_eda.groupby('instance')['makespan'].min().values)]

In [193]:
df_ag_swap = pd.read_csv('../resultados/mesma populacao/mutacao swap/ag_mutacao_swap.csv',index_col=0)
df_ag_swap.style.format("{:.2f}")
pd.set_option('display.float_format', lambda x: '%.3f' % x)
df_ag_min_swap = df_ag_swap.loc[df_ag_swap['makespan'].isin(df_ag_swap.groupby('instance')['makespan'].min().values)]

In [194]:
df_eda_swap = pd.read_csv('../resultados/mesma populacao/mutacao swap/eda_mutacao_swap.csv',index_col=0)
df_eda_swap.style.format("{:.2f}")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [195]:
df_eda_min_swap = df_eda_swap.loc[df_eda_swap['makespan'].isin(df_eda_swap.groupby('instance')['makespan'].min().values)]
df_ags = pd.concat([df_ag, df_ag_swap], 
                   axis='columns', keys=['First', 'Second'])

In [196]:
count_swap = 0
count_simp = 0
for i in range(len(df2)):
    print(df_ag_min_swap.iloc[i]['makespan'], df_ag_min.iloc[i]['makespan'])
    if df_ag_min_swap.iloc[i]['makespan'] < df_ag_min.iloc[i]['makespan']:
        print("swap")
        count_swap += 1
    else:
        count_simp += 1
count_simp, count_swap

100141.42523800004 100130.66156800004
4689160.036982999 4620447.925782002
135630.963501 133609.92913600005
3588.824516000001 3582.7991020000013
76158.26426499999 75520.472098
3240628.3557139994 3108091.357506
111723.49691899995 109428.979561
2696.0347810000007 2644.8650339999995
158410.420654 157462.00725299993
8245526.930664 8251583.0
swap
271341.7598370001 268048.32483
5344.584729 5320.018936999997

(11, 1)

In [197]:
count_swap = 0
count_simp = 0
for i in range(len(df2)):
    if df_eda_min_swap.iloc[i]['makespan'] < df_eda_min.iloc[i]['makespan']:
        
        count_swap += 1
    else:
        count_simp += 1
count_simp, count_swap

(8, 4)

In [198]:
count_eda = 0
count_ag = 0
for i in range(len(df2)):
    if df_eda_min_swap.iloc[i]['makespan'] < df_ag_min_swap.iloc[i]['makespan']:
        count_eda += 1
    else:
        count_ag += 1
count_eda, count_ag

(10, 2)

In [199]:
df_eda_min2 = df_eda_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])
df_eda_min_swap2 = df_eda_min_swap.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])


df_ags = pd.concat([df_eda_min2.reset_index(), df_eda_min_swap2.reset_index()], 
                   axis='columns', keys=['EDA Mutação Simples', 'EDA Mutação Swap'])
df_ags

   EDA Mutação Simples                                            \
                 index    makespan elitismo    instance mutation
0                    3   99059.431   10.000  u_s_hilo.0   30.000
1                    7 4604010.228   10.000  u_s_hihi.0   30.000
2                    9  131241.166   10.000  u_s_lohi.0   10.000
3                   14    3586.450   10.000  u_s_lolo.0   20.000
4                   19   75196.376   10.000  u_i_hilo.0   30.000
5                   22 3104138.296   10.000  u_i_hihi.0   20.000
6                   26  111289.185   10.000  u_i_lohi.0   20.000
7                   31    2614.296   10.000  u_i_lolo.0   30.000
8                   33  160356.762   10.000  u_c_hilo.0   10.000
9                   37 8128168.568   10.000  u_c_hihi.0   10.000
10                  42  267103.582   10.000  u_c_lohi.0   20.000
11                  46    5381.139   10.000  u_c_lolo.0   20.000

   EDA Mutação Swap
              index    makespan elitismo    instance mutation
0                 4   99563.054   10.000  u_s_hilo.0   30.000
1                 6 4621486.670   10.000  u_s_hihi.0   10.000
2                12  132641.710   10.000  u_s_lohi.0   30.000
3                14    3585.936   10.000  u_s_lolo.0   10.000
4                17   75207.257   10.000  u_i_hilo.0    0.000
5                22 3068641.279   10.000  u_i_hihi.0   10.000
6                25  110568.715   10.000  u_i_lohi.0    0.000
7                32    2609.982   10.000  u_i_lolo.0   30.000
8                33  160807.828   10.000  u_c_hilo.0    0.000
9                39 8142691.785   10.000  u_c_hihi.0   20.000
10               42  271166.439   10.000  u_c_lohi.0   10.000
11               45    5409.638   10.000  u_c_lolo.0    0.000

In [200]:
df_ag_min2 = df_ag_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])
df_ag_min_swap2 = df_ag_min_swap.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])


df_ags = pd.concat([df_ag_min2.reset_index(), df_ag_min_swap2.reset_index()], 
                   axis='columns', keys=['AG Mutação Simples', 'AG Mutação Swap'])
df_ags

   AG Mutação Simples                                            \
                index    makespan elitismo    instance mutation
0                   2  100130.662   10.000  u_s_hilo.0   10.000
1                   8 4620447.926   10.000  u_s_hihi.0   20.000
2                  14  133609.929   10.000  u_s_lohi.0   30.000
3                  17    3582.799   10.000  u_s_lolo.0   10.000
4                  24   75520.472   10.000  u_i_hilo.0   30.000
5                  29 3108091.358   10.000  u_i_hihi.0   30.000
6                  34  109428.980   10.000  u_i_lohi.0   30.000
7                  39    2644.865   10.000  u_i_lolo.0   30.000
8                  43  157462.007   10.000  u_c_hilo.0   20.000
9                  49 8251583.000   10.000  u_c_hihi.0   30.000
10                 54  268048.325   10.000  u_c_lohi.0   30.000
11                 58    5320.019   10.000  u_c_lolo.0   20.000

   AG Mutação Swap
             index    makespan elitismo    instance mutation
0                3  100141.425   10.000  u_s_hilo.0   30.000
1                7 4689160.037   10.000  u_s_hihi.0   30.000
2               11  135630.964   10.000  u_s_lohi.0   30.000
3               14    3588.825   10.000  u_s_lolo.0   20.000
4               18   76158.264   10.000  u_i_hilo.0   20.000
5               20 3240628.356   10.000  u_i_hihi.0    0.000
6               25  111723.497   10.000  u_i_lohi.0   10.000
7               31    2696.035   10.000  u_i_lolo.0   30.000
8               34  158410.421   10.000  u_c_hilo.0   20.000
9               39 8245526.931   10.000  u_c_hihi.0   30.000
10              43  271341.760   10.000  u_c_lohi.0   30.000
11              45    5344.585   10.000  u_c_lolo.0   10.000

In [202]:
df_ag_min2 = df_ag_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])
df_eda_min2 = df_eda_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])


df_ags = pd.concat([df_ag_min2.reset_index(), df_eda_min2.reset_index()], 
                   axis='columns', keys=['AG Mutação Simples', 'EDA Mutação Simples'])
df_ags

   AG Mutação Simples                                            \
                index    makespan elitismo    instance mutation
0                   2  100130.662   10.000  u_s_hilo.0   10.000
1                   8 4620447.926   10.000  u_s_hihi.0   20.000
2                  14  133609.929   10.000  u_s_lohi.0   30.000
3                  17    3582.799   10.000  u_s_lolo.0   10.000
4                  24   75520.472   10.000  u_i_hilo.0   30.000
5                  29 3108091.358   10.000  u_i_hihi.0   30.000
6                  34  109428.980   10.000  u_i_lohi.0   30.000
7                  39    2644.865   10.000  u_i_lolo.0   30.000
8                  43  157462.007   10.000  u_c_hilo.0   20.000
9                  49 8251583.000   10.000  u_c_hihi.0   30.000
10                 54  268048.325   10.000  u_c_lohi.0   30.000
11                 58    5320.019   10.000  u_c_lolo.0   20.000

   EDA Mutação Simples
                 index    makespan elitismo    instance mutation
0                    3   99059.431   10.000  u_s_hilo.0   30.000
1                    7 4604010.228   10.000  u_s_hihi.0   30.000
2                    9  131241.166   10.000  u_s_lohi.0   10.000
3                   14    3586.450   10.000  u_s_lolo.0   20.000
4                   19   75196.376   10.000  u_i_hilo.0   30.000
5                   22 3104138.296   10.000  u_i_hihi.0   20.000
6                   26  111289.185   10.000  u_i_lohi.0   20.000
7                   31    2614.296   10.000  u_i_lolo.0   30.000
8                   33  160356.762   10.000  u_c_hilo.0   10.000
9                   37 8128168.568   10.000  u_c_hihi.0   10.000
10                  42  267103.582   10.000  u_c_lohi.0   20.000
11                  46    5381.139   10.000  u_c_lolo.0   20.000

In [204]:
df_eda_sem = pd.read_csv('../eda_sem_mutacao.csv',index_col=0)
df_eda_sem.style.format("{:.2f}")
df_eda_sem['mutation'] = 0.000
pd.set_option('display.float_format', lambda x: '%.3f' % x)
df_eda_sem_min = df_eda_sem.loc[df_eda_sem['makespan'].isin(df_eda_sem.groupby('instance')['makespan'].min().values)]

In [214]:
df_eda_min2 = df_eda_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])
df_eda_sem_min2 = df_eda_sem_min.drop(columns=['jobs','machines','exec_time','selection_method', 'to_matrix_percentage', 'numInd', 'numGen'])


df_ags = pd.concat([df_eda_min2.reset_index(), df_eda_sem_min2.reset_index()], 
                   axis='columns', keys=['EDA Mutação Simples', 'EDA Sem Mutação'])
p = []
for i in range(len(df_eda_sem_min2)):
    p.append((1-df_eda_sem_min2.iloc[i]['makespan']/df_eda_min2.iloc[i]['makespan'])*100)
    
#df_ags['melhoria'] = p
    


df_ags

   EDA Mutação Simples                                            \
                 index    makespan elitismo    instance mutation
0                    3   99059.431   10.000  u_s_hilo.0   30.000
1                    7 4604010.228   10.000  u_s_hihi.0   30.000
2                    9  131241.166   10.000  u_s_lohi.0   10.000
3                   14    3586.450   10.000  u_s_lolo.0   20.000
4                   19   75196.376   10.000  u_i_hilo.0   30.000
5                   22 3104138.296   10.000  u_i_hihi.0   20.000
6                   26  111289.185   10.000  u_i_lohi.0   20.000
7                   31    2614.296   10.000  u_i_lolo.0   30.000
8                   33  160356.762   10.000  u_c_hilo.0   10.000
9                   37 8128168.568   10.000  u_c_hihi.0   10.000
10                  42  267103.582   10.000  u_c_lohi.0   20.000
11                  46    5381.139   10.000  u_c_lolo.0   20.000

   EDA Sem Mutação
             index    makespan elitismo    instance mutation
0                2   99947.513   10.000  u_s_hilo.0    0.000
1                6 4625428.280   10.000  u_s_hihi.0    0.000
2                8  135229.987   10.000  u_s_lohi.0    0.000
3               13    3593.802   10.000  u_s_lolo.0    0.000
4               19   76000.789   10.000  u_i_hilo.0    0.000
5               20 3122442.812   10.000  u_i_hihi.0    0.000
6               24  112317.071   10.000  u_i_lohi.0    0.000
7               29    2627.175   10.000  u_i_lolo.0    0.000
8               33  160049.507   10.000  u_c_hilo.0    0.000
9               39 8271411.055   10.000  u_c_hihi.0    0.000
10              43  269420.748   10.000  u_c_lohi.0    0.000
11              46    5352.345   10.000  u_c_lolo.0    0.000